### ISSUE TITLE
Hitbox streams stay live

### ISSUE THREAD

**Issue by jarlave** [laurencee/Livestream.Monitor#13]
Hey,

is it just me that the hitbox streams stay live (after the stream ended).
The only way to get the stream to show offline is to remove the streamer and add him again.

**Comment by laurencee** [comment]
Yep that's probably right looking at the code.

I'll sort that out in the next release.

**Comment by laurencee** [comment]
Quick note, you could also restart the app rather than removing/adding back the stream.

**Comment by laurencee** [comment]
https://github.com/laurencee/Livestream.Monitor/releases/tag/2.2.1
