### ISSUE TITLE
Importing issue

### ISSUE THREAD

**Issue by GXTX** [laurencee/Livestream.Monitor#14]
From a _base install_ there's an issue while trying to import for the first time. After you get the error and try again it works perfectly fine. 
![showing issue 1](https://i.imgur.com/Wy2PuGr.png)

Finally it will show the people you are following but will show they are all offline with 0 viewers, reopening the application fixes this issue.
![showing issue 2](https://i.imgur.com/IogOMby.png)
![fixed](https://i.imgur.com/U0tFhUW.png "fixed")

**Comment by laurencee** [comment]
Thanks I'll take a look at this. With the import scenario does clicking the refresh button update the streams correctly without having to restart the application?

I probably need to make it do that immediately after import finishes.

**Comment by GXTX** [comment]
It allows you to click the refresh button but nothing happens until you restart.

**Comment by laurencee** [comment]
Fixed in https://github.com/laurencee/Livestream.Monitor/releases/tag/2.4.2
