### ISSUE TITLE
Issues with config files

### ISSUE THREAD

**Issue by GXTX** [laurencee/Livestream.Monitor#15]
If you have a blank settings.json the program will startup and work but not have the livestreamer and chrome path filled out and will not overwrite the blank file with the default settings.

And if you create a blank livestreams.json file the program will crash on startup.

**Comment by laurencee** [comment]
I'll take a look, do you know how did you ended up with a blank settings.json file?

**Comment by GXTX** [comment]
I was wanting to reset everything,

**Comment by laurencee** [comment]
Fixed in https://github.com/laurencee/Livestream.Monitor/releases/tag/2.4.2
