### ISSUE TITLE
Can you contact me in anyway on using this as an example?

### ISSUE THREAD

**Issue by HolyBreadstick** [laurencee/Livestream.Monitor#17]
I am having trouble understanding the logic behind how the video is actually played. I am trying to create a similar project using WPF and this would be really great if you could help me with code on the video side. [email](mailto:baileymiller@live.com)

**Comment by laurencee** [comment]
WPF isn't doing anything to run the video, that's being launched by http://docs.livestreamer.io/

This is just a GUI wrapper for livestreamer with the addition of monitoring livestreams from a few different sites.
