### ISSUE TITLE
Importing livestreams from twitch.tv doesn't do anything

### ISSUE THREAD

**Issue by thingisbroken** [laurencee/Livestream.Monitor#18]
On a clean install. When I enter a twitch username in the import section, it briefly shows the list of followed channels. This list disappears immediately and is not saved in livestreams.json. 

Manually adding livestreams does seem to work.
EDIT Just to confirm for future reference, I am using 2.4.2

**Comment by laurencee** [comment]
Hmm are you using 2.4.2 which was just released? That fixed an import issue in 2.4.1.

I just tested with my twitch username from a clean install and it imported correctly.

**Comment by laurencee** [comment]
Oh I can see an issue with the file not saving actually. 
I'll get right on that, thanks for the report.

**Comment by laurencee** [comment]
Try 2.4.3 and let me know if that fixes it for you...

**Comment by thingisbroken** [comment]
Yup, 2.4.3 saves the imported streams to livestreams.json, thanks for the quick fix!

**Comment by laurencee** [comment]
Thanks for the quick confirmation!
