### ISSUE TITLE
Beam.pro support

### ISSUE THREAD

**Issue by jarlave** [laurencee/Livestream.Monitor#20]
Using you tool a long time now, I rly liek it!
But are you going to implement beam.pro? (is supported in the nightly from 2. Feb.)

**Comment by laurencee** [comment]
I'll take a look at it, I hadn't heard of beam.pro before.

**Comment by laurencee** [comment]
I'm most of the way through adding this, gonna need another hour or 2 to test when I get the time. Hopefully in a few days.

**Comment by jarlave** [comment]
you are really fast, thanks!

**Comment by laurencee** [comment]
Ok that's released now, raise issues if you run into any bugs thanks!

https://github.com/laurencee/Livestream.Monitor/releases/tag/2.7.0
