### ISSUE TITLE
Twitch.tv: No client ID specified

### ISSUE THREAD

**Issue by Tharn** [laurencee/Livestream.Monitor#21]
Hi,

Since today, LM throws errors when trying to update twitch streams or loading VOD lists. For lack of copypaste or a log, I'll just abbreviate it. Is there a debug option?

ExternalAPIs.HttpRequestWithStatusException: {"error":"Bad Request","status":400,"message":"No client id specified"} at
ExternalAPIs.HttpClientExtensions.<EnsureSuccessStatusCodeAsync>d__4.MoveNext() in H:\Programming\Git\Livestream.Monitor\ExternalAPIs\HttpClientExtensions.cs:line 49

A couple more, at.. same file:line 35, TwitchTvReadonlyClient.cs:line 12, TwitchApiClient.cs:line 209, VodListViewModel.cs:line 235

**Comment by laurencee** [comment]
Looks like twitch requires their api's to be called with either an OAuth token or a ClientID header.

Here's a link so you can fix livestreamer being able to launch streams: https://github.com/chrippa/livestreamer/issues/1456#issuecomment-247192307

I'll update the app soon to send what twitch needs.

**Comment by laurencee** [comment]
The latest release will fix your issue. Take note of the bolded text about the OAuth token for livestreamer.

https://github.com/laurencee/Livestream.Monitor/releases/tag/2.8.0
