### ISSUE TITLE
Hitbox.tv: VODs can't be played

### ISSUE THREAD

**Issue by Tharn** [laurencee/Livestream.Monitor#22]
Hey,

I can't seem to be able to play Hitbox VODs through Livestream Monitor. They're correctly listed with thumbnails and times and everything, but the 'Open Vod' button is greyed out and the 'Vod URL' is just a long string of hexadecimals.

**Comment by laurencee** [comment]
Hmm I think hitbox might have messed up their API:
http://developers.hitbox.tv/#get-video

I'm pretty sure that the media_file returned the video id you see in your url but now it seems to refer to a GUID type entity which I'm guessing is how they reference their videos in whatever database they're using behind the scenes.

**Comment by laurencee** [comment]
Looks like something might be going on with their vods:
https://twitter.com/hitboxliveHelp/status/779006903896666114

**Comment by Tharn** [comment]
Thanks for the heads up! I tried Hitbox for the first time today, otherwise I would've checked with Google first. Bad luck. ;)

**Comment by laurencee** [comment]
All good now, meant to use media_id from now on.

Fix incoming.
