### ISSUE TITLE
Twitch VOD URL

### ISSUE THREAD

**Issue by Tharn** [laurencee/Livestream.Monitor#24]
Twitch has changed where it keeps its files. Streamlink already has an issue open for it, so I'm not sure if this is a LM problem to begin with. I do know that LM displays the proper new URL when you click on a tile, and it works fine with screenshot and all. It just doesn't play.

If you change the URL displayed in LM when you click on a VOD from twitch.tv/videos/XXXXXXXXX to twitch.tv/user/v/XXXXXXXXX, they can be played.

I think this might be legacy functionality. Since twitch.tv/videos/XXXXXXXXX is the new layout - it probably just isn't parsed right by streamlink. Feel free to close this if it's not a LM problem.

**Comment by laurencee** [comment]
Kind of annoying because the /videos/ url still works on twitch website.

**Comment by laurencee** [comment]
This might get addressed by #25 if the new api returns the updated urls.

**Comment by laurencee** [comment]
I might just hack this one like you suggested since at least then the urls will just work without having to muck around with cut/paste.

**Comment by laurencee** [comment]
https://github.com/laurencee/Livestream.Monitor/releases/tag/2.9.1

**Comment by Tharn** [comment]
Appreciate it! Ironically 2.9.0 was fine once streamlink had gotten its own update to handle the twitch.tv/videos/XXXXXXXXX URL.
