### ISSUE TITLE
Update twitch api calls to V5

### ISSUE THREAD

**Issue by laurencee** [laurencee/Livestream.Monitor#25]
TwitchTv V3 API is being deprecated as of Feb 14 2017 and will be removed entirely in 2018.
https://dev.twitch.tv/docs/

- [ ] Use new v5 header
- [ ] Move from user names to user ids
- [ ] Investigate changing from offsets to cursors for paged queries

**Comment by laurencee** [comment]
Started playing around with this today, gonna take a bit more work than I originally thought due to the conversion of all the existing usernames into userids.

I'll probably need to use a caching system similar to youtube names to ids.
https://github.com/laurencee/Livestream.Monitor/blob/master/Livestream.Monitor/Model/ApiClients/YoutubeApiClient.cs#L116

**Comment by TaoziDB** [comment]
They moved from usernames to userids so that user can change name freely.

**Comment by laurencee** [comment]
That's generally what a display name is for.

**Comment by laurencee** [comment]
I've decided when I get around to this to store an additional displayname field in livestreams.json.

**Comment by laurencee** [comment]
https://blog.twitch.tv/the-new-twitch-api-be3fb2b078e6
Looks like this wont be happening as there's a newer API coming out that sounds much better suited for the sorts of calls I want to do.

The current API the app uses should remain fine until the end of next year according to this blog.

I'm more incentivised to use this newer API as it should have bulk calls for stuff I currently have to do individual calls for.
