### ISSUE TITLE
[QoL] Make chat popout work with any browser?

### ISSUE THREAD

**Issue by Tharn** [laurencee/Livestream.Monitor#27]
Hi again,

Popouts are generally pretty easy to do, all you need is to call the browser with an URL reading `https://www.twitch.tv/channel_goes_here/chat?popout=` in the case of Twitch, or `http://www.hitbox.tv/embedchat/channel_goes_here?autoconnect=true` for Hitbox. I don't know the others, but I assume the restriction to Chrome mostly has to do with fancy pop-out resizing and stuff?

It'd be handy to have it just call the default handler for http, if possible. Or having that as a fallback for people not using Chrome.

**Comment by laurencee** [comment]
Yeah the only reason it was setup for chrome was due to the resizing commands. Something to look into for sure.

**Comment by laurencee** [comment]
Oh the other reason was being able to tell chrome to open in a separate window it without showing the url bar through the --app command.

If you just launch the URL directly through the process it'll open in chrome as if it was just another tab and I presume it'll do the same for the other browsers which isn't desirable.

**Comment by laurencee** [comment]
It might be easier to just support the most common set of browsers people use (Chrome/IE/Firefox/Safari/Edge) and set launch parameters for them like I do with chrome currently. I doubt those launch parameters would have to be updated very often.

**Comment by Tharn** [comment]
Agreed, that should be fine. I would note though that it's a good idea not to tie these browsers to only one .exe. For Chrome/Chromium it happens to be the same .exe, but for Firefox/Waterfox/Cyberfox/PaleMoon it isn't. IE also has at least one other front-end using the same engine.

**Comment by laurencee** [comment]
Cheers for the info but FYI; It's not really something I'm looking at doing in the near future.

**Comment by Tharn** [comment]
I'm not seeing the big difference between Browser Path (Firefox) -> Select *.exe or Browser Path (Firefox) -> Select firefox.exe.

But it's your baby of course. I appreciate the help. ;)

**Comment by laurencee** [comment]
I need someway to know the type of browser it is so I can apply the correct arguments. Each browser has different switches to do the same thing -app does for chrome.

If I allowed for a *.exe filter on the file selection then an additional option menu would be required to let the app know what type of browser that exe represents.

**Comment by Tharn** [comment]
Yeah, that's why I meant to suggest something similar to what it is now. You'd basically select Chrome, Firefox, IE or Safari. And then the actual 'Open' dialogue could be accepting any kind of .exe file.

All the different Firefox brands should absolutely accept the same argument passed to them. And if they don't, your ass is covered by the fact that it simply states 'Firefox' in LM. It's just a 'will probably work' for everyone who doesn't use one of these.

**Comment by laurencee** [comment]
Yeah that'll probably be the plan when I get around to it at some stage :)

**Comment by Tharn** [comment]
Another thing I noticed. When LM opens Chrome or Chromium, it does not use the arguments put into HKEY_CLASSES_ROOT/(browser)/shell/open/command. Can this be done or does it have to be a custom call?

**Comment by laurencee** [comment]
There's not much to the chrome args: https://github.com/laurencee/Livestream.Monitor/blob/master/Livestream.Monitor/Model/StreamLauncher.cs#L70

What sort of arguments come from that registry key?

**Comment by Tharn** [comment]
All the commandline args that you can set i.e. for a taskbar shortcut, you can in the ROOT folder to be used when other programs want to open an executable. Such as a mail client pushing an URL to Chrome etc.

Chrome is notoriously tight with customization, which is why some of these can be useful. I use it for custom disk cache & media cache size and location. (http://peter.sh/experiments/chromium-command-line-switches/)

Hmm.. since the chat tab starts its own process anyway, I wonder if there's an easy way to just call it through the .html file association and **append** these two extra arguments.

**Comment by laurencee** [comment]
I'll have to investigate the registry key setup, doesn't sound like that much effort.

Is it just a single registry key with the arguments in it? If so then I'd just read the values and append them to the existing process start call.

**Comment by Tharn** [comment]
Yeah, it's just the one. But as I understand it they're not identical for Chrome and Chromium. Chromium in my case links to HKEY_CLASSES_ROOT\ChromiumHTM.N6GTCOIMPB7NK2S6RQAOQ3KAFY\. HKCR is where various machine and user settings are all gathered together, so it should be the right place to go. Might be easier to go by what .html or the chrome.exe links to rather than figure out the right folder by hand.

https://msdn.microsoft.com/de-de/library/windows/desktop/ms724475(v=vs.85).aspx

**Comment by laurencee** [comment]
I was thinking that since this hasn't gone anywhere yet maybe I can just add support for you to either point at chrome specifically or any other exe and it's up to the user to know that they've pointed to a valid browser that can accept the url as an argument.

This way at least you have chat functionality even if it doesn't resize/fit as nicely as the current chrome app version.

**Comment by Tharn** [comment]
Yeah, feel free to do that. Like I said, it's a total comfort feature.

**Comment by laurencee** [comment]
I played around with a few approaches and I think allowing a custom command line entry with some predefined settings for known browsers is a reasonable way to go.

There are still some changes I need to make such as notifying the user of the command that was executed if there are any errors detected but besides that I think it's pretty much good to go.

If you have the time I would appreciate if you could test it out. (backup your settings.json before using this)
[Livestream Monitor.2.9.6 (DEBUG).zip](https://github.com/laurencee/Livestream.Monitor/files/1034072/Livestream.Monitor.2.9.6.DEBUG.zip)

**Comment by Tharn** [comment]
It seems to work fine; tried with Palemoon Portable and Chromium. Palemoon created a full tab, Chromium created a pop-out. Chromium also created Cache directories, so I assume the HKEY_CLASSES_ROOT thing was a bit too involved after all.

I found `"ChatCommandLine": "\"C:\\Users\\Markus\\AppData\\Local\\Chromium\\Application\\chrome.exe\" --app={url} --window-size=350 -height=760",` in settings.json. I appended my command line flags manually and that seems to work well.

**Comment by laurencee** [comment]
Cheers, you can actually do that in the settings page directly. The chat command line text box is freely editable with whatever you want, the buttons are just there to have nice presets for common browsers.

**Comment by laurencee** [comment]
Thanks for testing, I'll get a release out in the next day or so.

**Comment by laurencee** [comment]
https://github.com/laurencee/Livestream.Monitor/releases/tag/2.9.6
