### ISSUE TITLE
Beam.pro changed name to mixer.com

### ISSUE THREAD

**Issue by jarlave** [laurencee/Livestream.Monitor#29]
Beam.pro changed the name to mixer.com
Currently the beam.pro API is still working, but I think this will change soon.
Maybe before this happens it should be changed here.

**Comment by laurencee** [comment]
Thanks for the update, I'll take a look into it this weekend.

Hitbox has also changed names/owners to smashcast, I have a branch waiting for me to do some more testing before pushing out a new build with the changes.
https://github.com/laurencee/Livestream.Monitor/tree/RenameHitboxToSmashcast

**Comment by laurencee** [comment]
Well I've done those changes but streamlink/livestreamer doesn't recognise the new names so it can't launch streams for them as of yet.

I'll probably be updating the app anyway since streamlink/livestreamer will have to update to accomodate the name change sooner or later.

**Comment by laurencee** [comment]
https://github.com/laurencee/Livestream.Monitor/releases/tag/2.9.6
