### ISSUE TITLE
Allow filtering streams based on online status

### ISSUE THREAD

**Issue by untergrundbiber** [laurencee/Livestream.Monitor#31]
Provide a checkbox to display only streams that are online/live

**Comment by laurencee** [comment]
Good idea, I'll have a think about how to display this on the screen.

**Comment by laurencee** [comment]
https://github.com/laurencee/Livestream.Monitor/releases/tag/2.10.0

**Comment by untergrundbiber** [comment]
Very nice, works fine! Thanks

**Comment by laurencee** [comment]
Was planning on doing it the day after I saw your message but Divinity 2 is a pretty addictive game.
