### ISSUE TITLE
How to monitoring youtube channels without username?

### ISSUE THREAD

**Issue by thejustsoul** [laurencee/Livestream.Monitor#35]
How to monitoring youtube channels without username?
`youtube/channel/RaNDoMSymBolSexaMPle/`

**Comment by laurencee** [comment]
Think I need to add support for monitoring youtube channels via channel name rather than just username.

I don't think there's a way to get around it with the current version of Livestream.Monitor

**Comment by laurencee** [comment]
I'll see if I can sort this out this weekend.

**Comment by laurencee** [comment]
https://github.com/laurencee/Livestream.Monitor/releases/tag/2.11.1 should address this. Let me know if run into issues.
