### ISSUE TITLE
Save Settings requires chrome.exe

### ISSUE THREAD

**Issue by Tharn** [laurencee/Livestream.Monitor#4]
Livestream Monitor is usable without Chrome as you said, but for the Save button to work you need to specify a valid chrome.exe. One workaround is to create a stub chrome.exe somewhere, but it'd be nice if a blank or invalid path didn't break that functionality.

Pretty cool program, by the way.

**Comment by laurencee** [comment]
Thanks for the bug report, I'll get that sorted out.
