### ISSUE TITLE
Popup doesnt show when youtube channel goes live

### ISSUE THREAD

**Issue by nicfedor** [laurencee/Livestream.Monitor#40]
Hey. I added my own youtube channel on this soft but when i start streaming popup in right corner doesn't show. I  tracked to this

private void LivestreamsOnCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (LivestreamModel livestream in e.NewItems)
                {
                    HookLivestreamChangeEvents(livestream);
                }
            }

            if (e.OldItems != null)
            {
                foreach (LivestreamModel removedLivestream in e.OldItems)
                {
                    UnhookLivestreamChangeEvents(removedLivestream);
                }
            }
        }

but e doesn't contain any livestreams so HookLivestreamChangeEvents(livestream) never called and pop up notification never shows. Why is that? I'm definitely streaming, i see it on youtube. And status icon in list of channels change it's color to green, but popup never shows.

**Comment by laurencee** [comment]
Are you running version 2.11.2?

I'll take a look this evening and see what's happening, thanks for the report.

**Comment by nicfedor** [comment]
Yes. 2.11.2.

2017-12-01 8:39 GMT+05:00 Laurence0x03 <notifications@github.com>:

**Comment by laurencee** [comment]
I see the issue, will sort it out.

**Comment by laurencee** [comment]
https://github.com/laurencee/Livestream.Monitor/releases/tag/2.11.3

Let me know if you have anymore issues.
