### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by nicfedor** [laurencee/Livestream.Monitor#42]
Hey. I'm developing my own soft. I desperately need to implement youtube popup notifications in my soft. Can we contact somehow to chat about it?

**Comment by laurencee** [comment]
You can adapt the code I have here: https://github.com/laurencee/Livestream.Monitor/blob/master/Livestream.Monitor/Model/NotificationHandler.cs

Outside of that I don't have time to help sorry.
