### ISSUE TITLE
'Hide stream output on load' stopped working

### ISSUE THREAD

**Issue by Tharn** [laurencee/Livestream.Monitor#43]
Hi there,

Ever since Streamlink updated (I'm guessing this is why), the 'hide on load' option does not seem to work anymore. The console window does not hide when watching a stream or a VOD, but it does close when the media player closes.

**Comment by laurencee** [comment]
I'm running streamlink 0.13.0 which is the latest at the time of writing and don't appear to have this issue and am unsure how to replicate it.

Is there some specific stream this does it on? 
Does it happen for all of the stream providers? i.e. twitch/youtube/smashcast/mixer

**Comment by Tharn** [comment]
I tried both Twitch and Mixer for this, so that means several streams and several providers.

I also think that I had the option set, then un-ticked the box on the console output one time.. after which neither option nor the tick box work anymore. I didn't think that was the reason and assumed it had to be some update.

Will test this some more later.

**Comment by Tharn** [comment]
It still doesn't work. I have been looking at the config file, and `"HideStreamOutputMessageBoxOnLoad": true,` should correspond with the LM setting? There is no other way this setting could permanently screw itself, right?

Also, playing around with this I noticed the checkbox setting on the console output does not always set the setting correctly, i.e.:

- Disable `Hide Stream Output On Load`, then load a VOD -> checkbox is not marked.
- Disable `Hide Stream Output On Load`, then load a VOD and mark the checkbox -> Setting is still disabled. If you close the VOD and enable the setting, the `Save` option acts as if it was enabled all along.
- Enable `Hide Stream Output On Load`, then load a VOD -> checkbox is marked.
- Enable `Hide Stream Output On Load`, then load a VOD and unmark the checkbox -> Setting is still enabled. If you close the VOD and disable the setting, the `Save` option acts as if it was disabled all along.

**Comment by laurencee** [comment]
Ohh I think i see the issue

`if (args.Data.StartsWith("[cli][info] Starting player") ...)`
https://github.com/laurencee/Livestream.Monitor/blob/master/Livestream.Monitor/Model/StreamLauncher.cs#L246

**Comment by laurencee** [comment]
https://github.com/laurencee/Livestream.Monitor/releases/tag/2.11.4
