### ISSUE TITLE
Error refreshing livestreams

### ISSUE THREAD

**Issue by Jakeeeeeeee** [laurencee/Livestream.Monitor#45]
Constantly getting this randomly at multiple streams at start of the program.
https://i.gyazo.com/8bea767d845f7c36f6161b526c2af1f4.png
final effect
https://i.gyazo.com/bbaba625264f63a05114c87fcf54b160.png

**Comment by laurencee** [comment]
The errors showing `not found` in that list are twitchtv saying a channel with that name doesn't exist (either they were banned or they renamed their channel). If they're just temporarily banned then you can leave them but if they renamed their channel or were permanently banned you should remove them from your list so you don't get the error message every time.

The other error, `A connection attempt failed...` is most likely be a connectivity problem between your machine and the twitch servers.

**Comment by Jakeeeeeeee** [comment]
Nope, all those channels with error from the screenshot except of three are alive and well. As I said it's completely random getting that error of connection, basically every channel was exposed to get it since every start of the program gives bunch of these errors. Was trying to figure what causes it, it may be that program is "confused" with the querying whenever u keep the dead channels but that's just my n00b theory.

**Comment by laurencee** [comment]
So I visited the first error `not found` in the list of your screenshot (bearaj) and that page is down like I mentioned it would be:
https://www.twitch.tv/BearAJ
https://i.imgur.com/NnwJiIP.png

Second one with `not found` error message is also not available.
https://www.twitch.tv/hitch_live
https://i.imgur.com/NnwJiIP.png

**Comment by laurencee** [comment]
Please check the names of all of the ones with not found, if they were updated to a new channel name you can remove them from livestreamer and import from your follows again (or add them using the new channel name).

**Comment by Jakeeeeeeee** [comment]
How about any of these? 
https://i.gyazo.com/ecc03a7ab1159a7b7489688b211ea584.png
Deleted all the dead ones. Dude, I'm not fooling around, this shit is happening at every launch, random channels getting errors for no reason at all.

**Comment by laurencee** [comment]
I do understand, I was making sure you filtered out the channels that didn't exist at the time you launched the app (which would have always correctly popped up as errors) from the random channel connection query errors.

Would you mind uploading your `livestreams.json` file here? I would like to be able to test this locally, you might be getting rate limited which I haven't hit myself yet with 200~ twitch channels.

**Comment by Jakeeeeeeee** [comment]
It's barely above 100 channels
[livestreams.txt](https://github.com/laurencee/Livestream.Monitor/files/2707684/livestreams.txt)

**Comment by laurencee** [comment]
Cheers, I gave it a run on a couple of different devices I have here and there weren't any issues. I got a friend to give it a quick load up and no issues there either.

So I don't believe there's an issue with the application itself rather there's some issue with settings related to your device such as a proxy or some connectivity issues to the twitch api server.

When you have the issue with channels failing to connect, after clicking ignore for the channels that popup can you press refresh and see if the channels get properly?

**Comment by laurencee** [comment]
Yeah, that's the one.

I don't know if you have another device or another internet connection you can try it on but that'd be ideal so you'd at least know if it's specific to your machine/connection or not which is all I can surmise at this time.

Sorry, there's nothing else I can do at this time.
