### ISSUE TITLE
Error refreshing livestreams

### ISSUE THREAD

**Issue by Jakeeeeeeee** [laurencee/Livestream.Monitor#48]
https://gyazo.com/89c3e7a9cc5ba489f88a0753d0a11f26

No idea what just happened. Always had many errors (sadly still unresolved thing) but now it just looks dead.

**Comment by laurencee** [comment]
The api version being used right now is being shut down, needs to be addressed via #34

**Comment by laurencee** [comment]
The email I recieved from twitch around this around 2 months back:

Starting on August 12, 2019, we will begin implementing scheduled outage windows of v3 endpoints over several weeks ending with a complete shutdown of v3 endpoints on September 12, 2019. If you do not take action to migrate your application to v5 of the API, your application will experience outages during this time and will completely break on September 12. The expected scheduled outage windows are as follows:

August 12 – 15 minute shutdown starting at 11:00am Pacific
August 15 – 1 hour shutdown starting at 11:00am Pacific
August 21 – 6 hour shutdown starting at 11:00am Pacific
August 22 – 24 hour shutdown starting at 11:00am Pacific
September 5 – 24 hour shutdown starting at 11:00am Pacific
September 12 – Permanent shutdown starting at 11:00am Pacific
