### ISSUE TITLE
LM 2.12.3 can't connect

### ISSUE THREAD

**Issue by Tharn** [laurencee/Livestream.Monitor#51]
Getting this error, which I think suggests LM is trying to connect using Twitch API v3? It worked fine earlier today, maybe something on their end changed.

![Untitled](https://user-images.githubusercontent.com/13466852/64378712-94333380-d02d-11e9-93b0-d009f3c2269e.png)

**Comment by laurencee** [comment]
There's one feature that relies on the v3 api as helix has no alternative but that call failing shouldn't result in the app not initializing so I'll sort that out.

**Comment by laurencee** [comment]
https://github.com/laurencee/Livestream.Monitor/releases/tag/2.12.4
