### ISSUE TITLE
"Copy Stream URL" copies wrong URL for YT-Stream

### ISSUE THREAD

**Issue by untergrundbiber** [laurencee/Livestream.Monitor#52]
Hello
when I use "Copy Stream URL" in the context menu, the stream URL for YouTube streams is incorrect. It was still working before the helix update.

Example for NASA TV
URL copied by livestream monitor:
https://www.youtube.com/watch?v=NASAtelevision

Expected URL:
https://www.youtube.com/watch?v=21X5lGlDOfg

As you can see, just the channel name "NASAtelevision" is copied as a video-id instead of the correct video-id "21X5lGlDOfg" as before, and of course, YouTube only displays a "video not found" error

I hope you can fix this, I often use that to watch a stream in the browser instead of streamlink
Greetings and thanks for this awesome software :) 👍

**Comment by laurencee** [comment]
Thanks for the concise report, I probably wont get a chance to look at this until the weekend but hopefully it's an easy fix :)

**Comment by laurencee** [comment]
https://github.com/laurencee/Livestream.Monitor/releases/tag/2.12.6

Take note of the current bug in youtube's api that I listed in the release notes.
