### ISSUE TITLE
Long VOD titles displace info

### ISSUE THREAD

**Issue by Tharn** [laurencee/Livestream.Monitor#54]
I can confirm this with Twitch so far. VOD titles with several line breaks may push the video duration & recorded date down and out of view on the VOD button.

Would recommend only allowing 3 lines of title text so that the other two still have room.

**Comment by laurencee** [comment]
Any idea if this is still an issue? Twitch changed how they returned data a while back but I don't know if they still send through line breaks in titles of vods that cause issues.

**Comment by Tharn** [comment]
I just checked, and..
![Clipboard-1](https://github.com/laurencee/Livestream.Monitor/assets/13466852/d0241179-250a-41c3-b760-36b334b17b68)

If you want to check it, this is on Page 2 of Broadcasts of old Twitch streamer Jefmajor.

**Comment by laurencee** [comment]
I have a fix for this on an old branch that I never ported across, but couldn't find a stream to repro to see if I needed to port it over. Cheers.

**Comment by laurencee** [comment]
https://github.com/laurencee/Livestream.Monitor/releases/tag/2.13.9

**Comment by laurencee** [comment]
Actually still has an issue I gotta sort out...

**Comment by laurencee** [comment]
Found that twitch seems to allow embeding both windows and linux styles of linebreaks, so I need to handle stripping out both. Should be good now, page 5 of Jefmajor's vods looks correct to me.
