### ISSUE TITLE
All of the sudden none of the live ones are working?

### ISSUE THREAD

**Issue by Jakeeeeeeee** [laurencee/Livestream.Monitor#55]
https://gyazo.com/e932a73e7c3b5e598da411fecf4ce702

Same error everywhere.

**Comment by steffbp** [comment]
I can +1 this.
The issue seems to be Twitch only and related to the twitch api.
Launching a stream via the streamlink cli returns with the same error.

**Comment by laurencee** [comment]
Hmm mine is working locally as of this moment, maybe this has been fixed by twitch?

**Comment by laurencee** [comment]
Also that error is coming from streamlink itself which is not something fixable from this app since it just wraps a nice GUI around that command line tool.

**Comment by laurencee** [comment]
I forgot to say thank you for the report as it helps to indicate to others that they're not alone with these issues.

**Comment by Jakeeeeeeee** [comment]
I can confirm it's working again, didn't do nothing. Weird thing.

**Comment by Jakeeeeeeee** [comment]
Once again not working. Hopefully not for long.
