### ISSUE TITLE
410 Client Error

### ISSUE THREAD

**Issue by Jakeeeeeeee** [laurencee/Livestream.Monitor#56]
Seems like it became a permanent thing now. Since @laurencee said "that error is coming from streamlink itself which is not something fixable from this app" are we doomed and completely on twitch api devs mercy? 

https://discuss.dev.twitch.tv/t/410-gone-when-requesting-private-api-api-namespace-with-3rd-party-client-id/23060/1

Responses from twitch clearly states they're not not willing to help.

**Comment by laurencee** [comment]
Currently following this issue: https://github.com/streamlink/streamlink/issues/2680

There's an apparent work around here: https://github.com/streamlink/streamlink/issues/2680#issuecomment-552024753

**Comment by laurencee** [comment]
I just tested locally and the workaround linked above does work.

The streamlink `twitch.py` plugin to monitor can be found here: `C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins` - follow instructions in the workaround link.

**Additional instructions for livestream monitor:**

1. Edit your `streamlinkrc` config file in `%APPDATA%\streamlink` and delete/comment out any existing `twitch-oauth-token` setting
2. Close the livestream monitor app
3. Make a copy/backup of your livestream monitor `settings.json` file
4. Edit the settings.json file:
a. Delete the line containing `TwitchAuthToken` 
b. Change the setting `TwitchAuthTokenInLivestreamerConfig` from `false` to `true` (this is just a hack so livestream monitor doesn't ask you for authorization anymore)

Now you'll be able to launch streams again from livestream monitor.

**Comment by Jakeeeeeeee** [comment]
Works like a charm. Much appreciate!

**Comment by laurencee** [comment]
https://github.com/streamlink/streamlink/releases/tag/1.3.0
