### ISSUE TITLE
Top Streams -> Game Filter issues

### ISSUE THREAD

**Issue by Tharn** [laurencee/Livestream.Monitor#58]
(This is for Twitch.TV)

When using the Top Streams & Game Filter options, LM will correctly show the first 15 streams ordered by viewers. It will not show the country flags anymore, and using the < > buttons at the bottom will not flick pages anymore but will load the same 15 streams every time.

**Comment by laurencee** [comment]
Thanks, the newer twitch api being used does paging significantly differently than the old one so I'll need to figure out a good way to handle it.

The old one was just just requesting a number of items and the current offset (how many items to skip), the new one you need to provide some unique paging id to go to the next page so I'll have to store that in the twitch provider while you're on the top streams tab (and clear correctly on leaving).

**Comment by Tharn** [comment]
With v. 2.12.9, I can't get any top streams filtered by game anymore. It just gives me this:

![Untitled](https://user-images.githubusercontent.com/13466852/84928511-ca2e3980-b0ce-11ea-83db-7717e8191685.png)

**Comment by laurencee** [comment]
Cheers, I'll take a look at it soon.

**Comment by laurencee** [comment]
Sorry I've been away for a while but I'm back again now and have this fixed locally, will push a release out soon.

**Comment by Tharn** [comment]
Thanks for the fix!
Unfortunately the 'page buttons do nothing' thing still persists.

**Comment by laurencee** [comment]
Yep that's a separate issue, could you create one just specific to that problem? It requires a fair bit of effort to fix compared to this stuff that was done.

**Comment by laurencee** [comment]
Yep that's a separate issue than what was fixed. When I came back to look at this I only noticed the obvious error message when entering an unknown game name.

Could you create a github issue just specific to that paging problem? It requires a fair bit of effort to fix compared to this stuff that was done.

**Comment by laurencee** [comment]
Forgot to mention that I had also fixed the flag issue but hadn't checked in that for the last release.
