### ISSUE TITLE
Error adding streams

### ISSUE THREAD

**Issue by Gettinglucky** [laurencee/Livestream.Monitor#59]
Trying to import or add any streams from twitch results in the following error
{"error":"Unauthorized","status":401,"message";OAuth token is missing"}
I have added this to the config files and set to true, I have added the OAuth in the streamlink config, no longer shows anything and unable to add channels.  Installed and wiped all settings still the same result.
If I reload my old settings it shows all streams offline and does not allow anything else to be added.

**Comment by Jakeeeeeeee** [comment]
https://gyazo.com/45d0bb3dabcd0dbdda817fea3f0ef236

All seems offline even though I still watch one of many live ones which I opened some time ago and is still streaming (atm 5h20m live so something must have happened in the meantime)

**Comment by laurencee** [comment]
Something going on/off with twitch API, not sure what the go is but it's nothing specific to this app right now. 

Thanks for the report anyway.

**Comment by laurencee** [comment]
https://github.com/laurencee/Livestream.Monitor/releases/tag/2.12.7

**Comment by Jakeeeeeeee** [comment]
https://gyazo.com/3d92ea6532e2481f52fff007654907ba happening again

https://gyazo.com/239e2651dab226182de4f8ee14ecd840 fix ain't working for me

**Comment by laurencee** [comment]
That's a different issue than what I fixed. The one I fixed was an error message that said the "Client ID and OAuth token do not match".

I'll take a look into that issue, it's due to not having any twitch auth token. Previously that was obtained automatically the first time you tried to add/import anything from twitch but I dont think that method is working right now.

**Comment by laurencee** [comment]
Ok I think I've figured this one out, build should be coming soon @Jakeeeeeeee

**Comment by laurencee** [comment]
@Jakeeeeeeee Let me know if this fixes your issue: https://github.com/laurencee/Livestream.Monitor/releases/tag/2.12.8

**Comment by laurencee** [comment]
@Gettinglucky Give it a go when you get the chance, sorry for the delay.

**Comment by Jakeeeeeeee** [comment]
for a second there wasn't sure but looks good i think, as always thx for the super fast reaction! bare in mind it may not be the last word from twitch since yesterday it all came back to be working again after few hours, so probably they ain't finished with whatever they're doin.

**Comment by steffbp** [comment]
I've just tested 2.12.8.
It seems to be working :)

Nice work!

**Comment by laurencee** [comment]
Thanks all
