### ISSUE TITLE
[2.12.8] One or more errors occurred

### ISSUE THREAD

**Issue by Tharn** [laurencee/Livestream.Monitor#60]
Hi,
I get this error message at every LM startup, but there appears to be no log or way to check what the errors actually are.
![Untitled](https://user-images.githubusercontent.com/13466852/81273812-bd3e1500-904f-11ea-8dc9-3ba5f76a16dc.png)

**Comment by laurencee** [comment]
Yea I dont bother to log stuff unless it's an app crash.

I'll push through the actual error to the message box so you can see what's going on properly.

**Comment by laurencee** [comment]
Let me know what the actual error displayed is: https://github.com/laurencee/Livestream.Monitor/releases/tag/2.12.9

**Comment by Tharn** [comment]
I upgraded to 2.12.9 on both machines and the error stopped appearing. Odd. ;)

**Comment by laurencee** [comment]
I'll leave this open for a day or so, shouldn't be any differences from .8 -> .9 as I didn't fix anything heh: https://github.com/laurencee/Livestream.Monitor/commit/cb6d13329d78b57855219da88c776a1114e283b2

**Comment by laurencee** [comment]
I also just noticed the typo in the static text, ah well..

**Comment by Tharn** [comment]
Can't reproduce it anymore. I'll reopen if anything happens.

**Comment by laurencee** [comment]
Something that came to mind was the youtube api can run out of its query limit pretty easily so if you have any youtube streams perhaps that's what was failing to query at startup.

**Comment by Tharn** [comment]
I'm pretty sure it was the new Twitch token stuff. That's the only kind of error I got on a subsequent reinstall when the error was actually logged.
