### ISSUE TITLE
Commercial break in porgress

### ISSUE THREAD

**Issue by Jakeeeeeeee** [laurencee/Livestream.Monitor#64]
Can anything be done about it? It breaks a lot of streams after the countdown is done. Sound gets distorted and video is lagging. Also pops up in the middle of the stream, not only on the beginning. Any way to bypass it entirely?

https://i.imgur.com/WRduGmg.png

**Comment by laurencee** [comment]
That would be up to streamlink to deal with as streamlink controls passing through the video segments to the player. 
Livestream Monitor doesn't handle any of that so there's nothing I can do about it sorry.

**Comment by laurencee** [comment]
@Jakeeeeeeee Looks like this is what you're talking about: https://github.com/streamlink/streamlink/issues/3165

**Comment by laurencee** [comment]
So from what I gather reading through that you want to have `twitch-disable-ads` in your `streamlinkrc` and make sure you dont have `player-passthrough=hls`.

You can also enable the low latency twitch stuff along with that by adding
```
twitch-low-latency
hls-live-edge=1
```

**Comment by Jakeeeeeeee** [comment]
well i suppose adding twitch-disable-ads helps at beginning because it delays the start of stream until it passes the ad time, not sure yet what happens if ad pops up later on. 

#player-passthrough=http,hls,rtmp  this is what i have on default, didn't notice any difference with or without hls parameter

**Comment by laurencee** [comment]
The new update might help you out: https://github.com/streamlink/streamlink/releases/tag/1.6.0

**Comment by Jakeeeeeeee** [comment]
thx for the all the info, works like a charm after update!
