### ISSUE TITLE
Add custom names to followed Youtube channels for when offline.

### ISSUE THREAD

**Issue by crim-sama** [laurencee/Livestream.Monitor#65]
When youtube channels without custom URLs are offline, their names default to the user ID that's just garbled numbers and letters. Would love a way to add custom names to each entry so I know which is which.

**Comment by laurencee** [comment]
Yea that's def something that needs to be worked on though the whole youtube setup needs a bit of a rework so people can authenticate with their own accounts. 

Right now it sort of uses a shared api to access data which results in hitting request limits pretty frequently and would only get worse the more people who use this appliaction.

I'll see if I can take a look this weekend but no promises on that.

**Comment by laurencee** [comment]
I didn't have enough time to sort this out, next time I get a chance I'll just look at fixing this and leave the youtube overhaul until later.

**Comment by laurencee** [comment]
Looks like I forgot about this until I reviewed issues today. Better late than never I suppose: https://github.com/laurencee/Livestream.Monitor/releases/tag/2.13.8

If your old livestreams from youtube don't have displaynames you can look up the channel id from a site like https://commentpicker.com/youtube-channel-id.php and set the value yourself (which is what I had to do for a few really old followed youtube channels).

**Comment by laurencee** [comment]
Ideally there should be some right click option on the channels in the GUI to be able to set this value, but at least there's a workaround by directly editing the `livestreams.json` file.
