### ISSUE TITLE
Show stream titles in player

### ISSUE THREAD

**Issue by phrwn** [laurencee/Livestream.Monitor#69]
Not sure if this is a setting or a feature request, but when I open streams in mpv it just shows the link in the header, rather than the stream title. When I open streams via Streamlink for Twitch GUI it shows the titles, so it is possible.

**Comment by laurencee** [comment]
Thanks for posting this issue.

I think it might be specific to MPV taking a quick look at the twitch gui code.
https://github.com/streamlink/streamlink-twitch-gui/blob/fa310904daf46cfa5733d84c34968ca8bcf0d751/src/config/players.json#L106

`--force-media-title \"{name} - {game} - {status}\"`

I'll take a look when I have the chance. It might be easiest for me to just add a new setting field to allow for custom args to be passed into streamlink and I just set some good default values there.

**Comment by phrwn** [comment]
It's definitely a useful feature, especially on streams that update their titles regularly. Thanks for looking into it.

**Comment by laurencee** [comment]
@phrwn So I just tested this without needing to make any app changes and it actually already works in VLC.

You just have to edit your streamlink config file and uncomment the `title={author} - {category} - {title}`.

**Comment by phrwn** [comment]
Looks like it works with MPV too! That's great. Thanks.
