### ISSUE TITLE
Twitch Authorization token not generating

### ISSUE THREAD

**Issue by smellylemur** [laurencee/Livestream.Monitor#77]
Hi,

When I try to import my twitch following list, the program goes to the url to generate a token. It only displays a message saying "Gone" at the top. I've looked at other closed issues but nothing seems to be working to generate an 0auth token, and bypassing does not work.

**Comment by laurencee** [comment]
Thanks for creating this issue, looks like the api endpoint that was used for authenticating has been deprecated. I'll look into changing over to the new endpoint ASAP.

**Comment by laurencee** [comment]
This should be fixed now in the [latest release](https://github.com/laurencee/Livestream.Monitor/releases/tag/2.13.7), let me know if you run into any more issues. :)
