### ISSUE TITLE
request aborted could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by Unalasgi** [laurencee/Livestream.Monitor#80]
heya when i open livestream monitor i get 
request aborted could not create SSL/TLS secure channel
thought it was twitches end but its still happening
hope you can fix

thanx

**Comment by laurencee** [comment]
Sorry, there's not enough information to work with here.

**Comment by Unalasgi** [comment]
forgot to say im using windows 7  error says request aborted
could not create ssl/tls secure channel hope it can be fixed

thanx

**Comment by laurencee** [comment]
Could you post a screenshot of the error?

From a quick research on this there are 2 main possible reasons this might occur:
1. Windows 7 does have TLS 1.2 enabled by default so you'll need to enable it on your end if it's not already. I've linked some guides below to do this.
2. Windows 7 does support the same set of secure connections as Windows 8/10/11 etc. so may not be fixable if the above doesn't work...

https://support.captureone.com/hc/en-us/articles/360014239757--Could-not-create-SSL-TLS-secure-channel-activation-error-on-Windows-7

https://stackoverflow.com/a/70674920/2631967

**Comment by Unalasgi** [comment]
enabled tls 1.2 with reg fix from page ya sent
rebooted started livestream but same error
here's a screenshot 
![Screenshot 2024-10-18 at 00-36-53 Screeny 2024 10 18 00 34 38 jpg (JPEG Image 1920 × 1080 pixels) — Scaled (67_)](https://github.com/user-attachments/assets/d7c2d136-233c-4cb6-85d4-0a3c889a4683)

**Comment by laurencee** [comment]
I'm unsure what the issue is, I have no Windows 7 machines to test with as that was EOL a while back now so this may not be solveable.

Could you try renaming your `livestreams.json` so you have a fresh instance and then see if the app starts up? 

Afterwards, try adding 1 twitch stream to see if that causes the issue. 

Do the same with a youtube livestream (if you watch those).

**Comment by Unalasgi** [comment]
renamed livestream.json app starts
but cant add a stream says 
error adding stream 
![Screenshot 2024-10-18 at 07-33-19 Screeny 2024 10 18 07 32 02 jpg (JPEG Image 1920 × 1080 pixels) — Scaled (67_)](https://github.com/user-attachments/assets/7dfeea84-345d-4850-b07c-730ce2d6ecc3)

**Comment by laurencee** [comment]
That'll be the same error but it's just not displaying for full message. 

Sorry, but there isn't anything else I can do at this time besides recommending moving on from Windows 7 as it doesn't natively support modern secure connection ciphersuites.

There's probably a way to add them but it's not something I can help with.
